LOYALTY_EVENT_REGISTRATION = 'registration'
LOYALTY_EVENT_TICKET_PURCHASE = 'ticket_purchase'
LOYALTY_EVENT_BIRTHDAY_PURCHASE = 'birthday_purchase'
LOYALTY_EVENT_RESTAURANT_PURCHASE = 'restaurant_purchase'

LOYALTY_EVENTS = {
    LOYALTY_EVENT_REGISTRATION,
    LOYALTY_EVENT_TICKET_PURCHASE,
    LOYALTY_EVENT_BIRTHDAY_PURCHASE,
    LOYALTY_EVENT_RESTAURANT_PURCHASE,
}
LOYALTY_REWARD_TYPES = {'fixed', 'percent'}
