PAYMENT_GATEWAY_FREEDOMPAY = 'freedompay'
PAYABLE_BRANCH_TICKET_ORDER = 'branch_ticket_order'
PAYMENT_CURRENCY_KZT = 'KZT'

PAYMENT_STATUS_CREATED = 'created'
PAYMENT_STATUS_PENDING = 'pending'
PAYMENT_STATUS_PAID = 'paid'
PAYMENT_STATUS_FAILED = 'failed'
PAYMENT_STATUS_CANCELED = 'canceled'
PAYMENT_STATUS_EXPIRED = 'expired'

TERMINAL_PAYMENT_STATUSES = {
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_FAILED,
    PAYMENT_STATUS_CANCELED,
    PAYMENT_STATUS_EXPIRED,
}
