DEFAULT_BRANCH_MENU = {
    'categories': [
        {'key': 'soups', 'title': 'Супы', 'display_order': 1, 'is_active': True},
        {'key': 'salads', 'title': 'Салаты', 'display_order': 2, 'is_active': True},
        {'key': 'pizza', 'title': 'Пицца', 'display_order': 3, 'is_active': True},
        {
            'key': 'main-courses',
            'title': 'Вторые блюда',
            'display_order': 4,
            'is_active': True,
        },
        {'key': 'fast-food', 'title': 'Фастфуд', 'display_order': 5, 'is_active': True},
        {'key': 'tea', 'title': 'Чай', 'display_order': 6, 'is_active': True},
    ],
    'items': [
        {
            'category_key': 'soups',
            'title': 'Куриный суп с домашней лапшой',
            'price_tenge': 1490,
            'image_url': 'https://loremflickr.com/800/600/chicken,noodle,soup?lock=101',
            'display_order': 1,
            'is_active': True,
        },
        {
            'category_key': 'soups',
            'title': 'Суп ребра',
            'price_tenge': 1890,
            'image_url': 'https://loremflickr.com/800/600/rib,soup?lock=102',
            'display_order': 2,
            'is_active': True,
        },
        {
            'category_key': 'soups',
            'title': 'Пельмени с говядиной',
            'price_tenge': 1390,
            'image_url': 'https://loremflickr.com/800/600/beef,dumplings?lock=103',
            'display_order': 3,
            'is_active': True,
        },
        {
            'category_key': 'soups',
            'title': 'Пельмени с курицей',
            'price_tenge': 1390,
            'image_url': 'https://loremflickr.com/800/600/chicken,dumplings?lock=104',
            'display_order': 4,
            'is_active': True,
        },
        {
            'category_key': 'salads',
            'title': 'Хрустящие баклажаны',
            'price_tenge': 2190,
            'image_url': 'https://loremflickr.com/800/600/eggplant,salad?lock=105',
            'display_order': 1,
            'is_active': True,
        },
        {
            'category_key': 'salads',
            'title': 'Цезарь с курицей',
            'price_tenge': 2390,
            'image_url': 'https://loremflickr.com/800/600/chicken,caesar,salad?lock=106',
            'display_order': 2,
            'is_active': True,
        },
        {
            'category_key': 'salads',
            'title': 'Салат «Греческий»',
            'price_tenge': 2390,
            'image_url': 'https://loremflickr.com/800/600/greek,salad?lock=107',
            'display_order': 3,
            'is_active': True,
        },
        {
            'category_key': 'salads',
            'title': 'Салат «Ачучук»',
            'price_tenge': 1490,
            'image_url': 'https://loremflickr.com/800/600/tomato,onion,salad?lock=108',
            'display_order': 4,
            'is_active': True,
        },
        {
            'category_key': 'salads',
            'title': 'Салат «Свежий»',
            'price_tenge': 1490,
            'image_url': 'https://loremflickr.com/800/600/fresh,vegetable,salad?lock=109',
            'display_order': 5,
            'is_active': True,
        },
        {
            'category_key': 'pizza',
            'title': 'Пепперони',
            'price_tenge': 2490,
            'image_url': 'https://loremflickr.com/800/600/pepperoni,pizza?lock=110',
            'display_order': 1,
            'is_active': True,
        },
        {
            'category_key': 'pizza',
            'title': 'Маргарита',
            'price_tenge': 2390,
            'image_url': 'https://loremflickr.com/800/600/margarita,pizza?lock=111',
            'display_order': 2,
            'is_active': True,
        },
        {
            'category_key': 'pizza',
            'title': 'Болоньезе',
            'price_tenge': 2890,
            'image_url': 'https://loremflickr.com/800/600/bolognese,pizza?lock=112',
            'display_order': 3,
            'is_active': True,
        },
        {
            'category_key': 'pizza',
            'title': '4 сезона',
            'price_tenge': 2890,
            'image_url': 'https://loremflickr.com/800/600/four,seasons,pizza?lock=113',
            'display_order': 4,
            'is_active': True,
        },
        {
            'category_key': 'pizza',
            'title': 'С курицей и грибами',
            'price_tenge': 2890,
            'image_url': 'https://loremflickr.com/800/600/chicken,mushroom,pizza?lock=114',
            'display_order': 5,
            'is_active': True,
        },
        {
            'category_key': 'pizza',
            'title': '4 сыра',
            'price_tenge': 2890,
            'image_url': 'https://loremflickr.com/800/600/four,cheese,pizza?lock=115',
            'display_order': 6,
            'is_active': True,
        },
        {
            'category_key': 'main-courses',
            'title': 'Манты домашние',
            'price_tenge': 2490,
            'image_url': 'https://loremflickr.com/800/600/manti,dumplings?lock=116',
            'display_order': 1,
            'is_active': True,
        },
        {
            'category_key': 'main-courses',
            'title': 'Курица в соусе терияки',
            'price_tenge': 2790,
            'image_url': 'https://loremflickr.com/800/600/teriyaki,chicken?lock=117',
            'display_order': 2,
            'is_active': True,
        },
        {
            'category_key': 'main-courses',
            'title': 'Мясная нарезка',
            'price_tenge': 5390,
            'image_url': 'https://loremflickr.com/800/600/charcuterie,meat,plate?lock=118',
            'display_order': 3,
            'is_active': True,
        },
        {
            'category_key': 'main-courses',
            'title': 'Сырная паста с сосиской',
            'price_tenge': 1790,
            'image_url': 'https://loremflickr.com/800/600/cheese,pasta,sausage?lock=119',
            'display_order': 4,
            'is_active': True,
        },
        {
            'category_key': 'main-courses',
            'title': 'Жареное ассорти со сметаной',
            'price_tenge': 1990,
            'image_url': 'https://loremflickr.com/800/600/fried,platter,sour,cream?lock=120',
            'display_order': 5,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Наггетсы',
            'price_tenge': 1590,
            'image_url': 'https://loremflickr.com/800/600/chicken,nuggets?lock=121',
            'display_order': 1,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Сырные палочки',
            'price_tenge': 1690,
            'image_url': 'https://loremflickr.com/800/600/mozzarella,sticks?lock=122',
            'display_order': 2,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Крылышки (16 шт)',
            'price_tenge': 4490,
            'image_url': 'https://loremflickr.com/800/600/chicken,wings?lock=123',
            'display_order': 3,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Чизбургер Beef',
            'price_tenge': 2090,
            'image_url': 'https://loremflickr.com/800/600/beef,cheeseburger?lock=124',
            'display_order': 4,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Чизбургер Chicken',
            'price_tenge': 1990,
            'image_url': 'https://loremflickr.com/800/600/chicken,burger?lock=125',
            'display_order': 5,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Клаб-сэндвич',
            'price_tenge': 1990,
            'image_url': 'https://loremflickr.com/800/600/club,sandwich?lock=126',
            'display_order': 6,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Фри',
            'price_tenge': 790,
            'image_url': 'https://loremflickr.com/800/600/french,fries?lock=127',
            'display_order': 7,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Картофельные дольки',
            'price_tenge': 790,
            'image_url': 'https://loremflickr.com/800/600/potato,wedges?lock=128',
            'display_order': 8,
            'is_active': True,
        },
        {
            'category_key': 'fast-food',
            'title': 'Картофельные лодочки',
            'price_tenge': 790,
            'image_url': 'https://loremflickr.com/800/600/potato,skins?lock=129',
            'display_order': 9,
            'is_active': True,
        },
        {
            'category_key': 'tea',
            'title': 'Черный / Зеленый',
            'price_tenge': 990,
            'image_url': 'https://loremflickr.com/800/600/black,green,tea?lock=130',
            'display_order': 1,
            'is_active': True,
        },
        {
            'category_key': 'tea',
            'title': 'Чай с молоком',
            'price_tenge': 1090,
            'image_url': 'https://loremflickr.com/800/600/milk,tea?lock=131',
            'display_order': 2,
            'is_active': True,
        },
        {
            'category_key': 'tea',
            'title': 'Ташкентский / Фруктовый / Ягодный / Манго-маракуйя / Малина-имбирь',
            'price_tenge': 1290,
            'image_url': 'https://loremflickr.com/800/600/fruit,tea?lock=132',
            'display_order': 3,
            'is_active': True,
        },
    ],
}
